### PR TITLE
Slater from RHF with single occupations

### PR DESCRIPTION
**Pull request by willwheelera**
The Slater object assigned up electrons to singly-occupied orbitals, and both up and down electrons to doubly-occupied ones. If there were multiple singly-occupied orbitals, this was an issue, since we usually want to keep up and down electrons balanced.

This PR divides up the singly-occupied orbitals among up and down electrons (alternating up, down, up down, etc).

### CODE REVIEW

**Comment by lkwagner** [comment]
This doesn't look correct to me. For ROHF, we explicitly don't want to keep the number of up and down electrons balanced.

**Comment by willwheelera** [comment]
I forgot about rohf. I'll make sure that works

**Comment by lkwagner** [comment]
If you forgot about rohf, then what is the use case of this modification? Can you give an example of code that should work but doesn't in the current implementation?

**Comment by willwheelera** [comment]
I wanted to manually change the occupation of an RHF object to create a determinant with a singles excitation. That would leave two half-filled orbitals, one up and one down. Or I could use a UHF object for that instead.

If we have a metal, with half-filled orbitals at different kpoints, should the half-filling electrons all be in the alpha channel? Our current implementation does this (and it looks like pyscf's ROHF and rohf.to_uhf() do too). Should we be able to have nalpha=nbeta even in the case of multiple half-filled orbitals?

**Comment by lkwagner** [comment]
For the first case, you should make a UHF object. 

For the second case, I'm not quite sure I understand the situation. You are saying that you have a KRKS or KRHF calculation and mo_occ looks like [ 2.0 2.0 1.0 1.0 0.0 0.0 ] for a given k-point? Or that it looks like:
[2.0 2.0 1.0 0.0 ...]
[2.0 2.0 1.0 0.0 ...] 
for two k-points? 

I don't think either of these cases are possible in RKS/RHF calculations, so that's why I'm confused.

**Comment by willwheelera** [comment]
Yeah the second case would be KROHF

**Comment by lkwagner** [comment]
OK, in that case you'd want them both to be up. That way it's a pure spin state. 

The state with them alternated up and down would be an Sz=0, but S^2 some superposition of states, plus with the orbitals optimized for the high S^2 case.

**Comment by lkwagner** [comment]
Closing this PR.

**Pull request closed without merging**
