### PR TITLE
add functions keys() and shapes() to accumulators

### PR DESCRIPTION
**Pull request by willwheelera**
Addressing issue #175 Accumulator functions

Energy, PGrad, OBDM, TBDM, Sq now all have the functions:
keys(): returns a set
shapes(): returns a dict whose keys are keys() and values are shapes. scalars have shape ()

I changed the definition of avg() in obdm and tbdm to the one-line version, since it does the same thing.
In tbdm I moved "ijkl" from avg() to a new function information(). I'm still not sure why we don't just use tbdm_acc._ijkl to get the array.

### CODE REVIEW

**Comment by lkwagner** [comment]
We don't use _ijkl because when we are doing analysis we may not want to construct a tbdm object. In general, the HDF file should contain all the information necessary to do the analysis.

**Comment by willwheelera** [comment]
got it. I added "ijkl" back to the avg() function

**Comment by lkwagner** [comment]
This now breaks test_accumulators.py

**Comment by lkwagner** [comment]
Note that this doesn't quite resolve the issue--the idea was to have the ijkl only stored per run, not per block. Although, one could make the argument that we *should* store it per block, in case of restarts, etc.. Hmm..

**Pull request merged**
